[global]
environment = "development"
storage_base_dir = "storage"

[api]
host = "127.0.0.1"
port = 8000

[ui]
host = "127.0.0.1"
port = 8501

[whitepaper]
pdf_subdir = "pdfs"
markdown_subdir = "markdowns"
images_subdir = "images"
tocs_subdir = "tocs"
model = "gemma4:31b-cloud"
vision_model = "gemma4:31b-cloud"

[tokenomics]
# For tokenomics data, settings in the future.

[social_media]
# For social media data, settings in the future.