import atexit
import difflib
import json
import logging
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Optional, cast
import unicodedata

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, pipeline  # type: ignore[import]

from core_shared.config import WhitepaperConfig


logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Models — loaded once at import time
# ---------------------------------------------------------------------------

_sentiment_pipeline = pipeline(
    "text-classification",
    model="ProsusAI/finbert",
    top_k=None,
    truncation=True,
    max_length=512,
)

_summarizer_tokenizer = AutoTokenizer.from_pretrained("sshleifer/distilbart-cnn-12-6")
_summarizer_model = AutoModelForSeq2SeqLM.from_pretrained("sshleifer/distilbart-cnn-12-6")


@atexit.register
def _cleanup_models() -> None:
    """Release HuggingFace pipeline resources on interpreter shutdown."""
    global _sentiment_pipeline, _summarizer_model, _summarizer_tokenizer
    del _sentiment_pipeline, _summarizer_model, _summarizer_tokenizer


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class SectionAnalysis:
    """Analysis results for a single whitepaper section.

    Attributes:
        word_count: Number of words in the section body.
        sentiment: Dominant sentiment label (positive / negative / neutral).
        score: Detailed scores in the form ``"pos=X.XX  neg=X.XX  neu=X.XX"``.
        resume: One-to-two sentence summary generated by DistilBART.
    """

    word_count: int
    sentiment: str
    score: str
    resume: str


# ---------------------------------------------------------------------------
# Analyzer
# ---------------------------------------------------------------------------

class SectionAnalyzer:
    """Semantic analysis pipeline for whitepaper sections.

    Pipeline:
        1. Load the extracted TOC (JSON) and Markdown files.
        2. Anchor TOC titles in the Markdown via fuzzy matching.
        3. For each section: run FinBERT sentiment analysis and DistilBART summarization.
        4. Persist results to JSON.

    Already-analysed documents are skipped automatically (UUID-based cache).
    """

    DEFAULT_SUMMARIZER_MAX_WORDS = 600
    DEFAULT_SENTIMENT_MAX_WORDS = 400
    DEFAULT_MIN_SUMMARY_WORDS = 30
    DEFAULT_MATCH_THRESHOLD = 0.75

    def __init__(
        self,
        output_dir: Optional[str] = None,
        sentiment_pipeline=None,  # type: ignore[assignment]
        summarizer_tokenizer=None,  # type: ignore[assignment]
        summarizer_model=None,  # type: ignore[assignment]
        summarizer_max_words: int = DEFAULT_SUMMARIZER_MAX_WORDS,
        sentiment_max_words: int = DEFAULT_SENTIMENT_MAX_WORDS,
        min_summary_words: int = DEFAULT_MIN_SUMMARY_WORDS,
        match_threshold: float = DEFAULT_MATCH_THRESHOLD,
    ):
        self.sentiment_pipeline = sentiment_pipeline or _sentiment_pipeline
        self.summarizer_tokenizer = summarizer_tokenizer or _summarizer_tokenizer
        self.summarizer_model = summarizer_model or _summarizer_model
        self.summarizer_max_words = summarizer_max_words
        self.sentiment_max_words = sentiment_max_words
        self.min_summary_words = min_summary_words
        self.match_threshold = match_threshold

        self.output_dir = Path(output_dir) if output_dir else None
        if self.output_dir:
            self.output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _already_processed(self, uuid: str) -> bool:
        """Return ``True`` if a JSON analysis file already exists for the given UUID."""
        if not self.output_dir:
            return False
        return (self.output_dir / f"{uuid}_analysis.json").exists()

    def _save(self, uuid: str, results: dict[str, SectionAnalysis]) -> None:
        """Persist analysis results to a JSON file."""
        if not self.output_dir:
            return
        path = self.output_dir / f"{uuid}_analysis.json"
        payload = {title: asdict(analysis) for title, analysis in results.items()}
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)

    def _load(self, uuid: str) -> dict[str, SectionAnalysis]:
        """Load previously persisted analysis results from the JSON file.

        Args:
            uuid: UUID of the document to load.

        Returns:
            A dictionary mapping section titles to :class:`SectionAnalysis` objects.

        Raises:
            ValueError: If no output directory is configured.
        """
        if not self.output_dir:
            raise ValueError("output_dir is not set.")
        path = self.output_dir / f"{uuid}_analysis.json"
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return {title: SectionAnalysis(**values) for title, values in data.items()}

    # ------------------------------------------------------------------
    # Text utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize(text: str) -> str:
        """Strip section numbering and punctuation, then lowercase and collapse whitespace.
        
        Applies Unicode NFKC normalisation to resolve typographic ligatures
        (e.g. 'ﬁ' → 'fi', 'ﬂ' → 'fl') before comparison.
        """
        text = unicodedata.normalize("NFKC", text)
        text = re.sub(r"^[\d]+[\.\d]*\s*", "", text)
        text = re.sub(r"[^\w\s]", " ", text)
        return " ".join(text.lower().split())

    @staticmethod
    def _truncate(text: str, max_words: int) -> str:
        """Truncate text to *max_words* words to stay within model token limits."""
        words = text.split()
        return " ".join(words[:max_words]) if len(words) > max_words else text

    # ------------------------------------------------------------------
    # Sentiment analysis
    # ------------------------------------------------------------------

    def _analyze_sentiment(self, text: str) -> tuple[str, str]:
        """Return the dominant sentiment label and a formatted score string.

        Args:
            text: Section body text to analyse.

        Returns:
            A tuple of (dominant_label, score_string) where score_string has
            the form ``"pos=0.87  neg=0.02  neu=0.11"``.
        """
        truncated = self._truncate(text, self.sentiment_max_words)
        raw_results = cast(
            list[list[dict[str, Any]]],
            self.sentiment_pipeline(truncated),
        )
        results = raw_results[0]

        scores: dict[str, float] = {
            str(r["label"]): round(float(r["score"]), 2)
            for r in results
        }
        dominant = max(scores, key=lambda k: scores[k])
        score_str = (
            f'pos={scores.get("positive", 0.0):.2f}  '
            f'neg={scores.get("negative", 0.0):.2f}  '
            f'neu={scores.get("neutral", 0.0):.2f}'
        )
        return dominant, score_str

    # ------------------------------------------------------------------
    # Summarization
    # ------------------------------------------------------------------

    def _summarize(self, text: str) -> str:
        """Return a one-to-two sentence extractive summary of the input text."""
        truncated = self._truncate(text, self.summarizer_max_words)
        if len(truncated.split()) < self.min_summary_words:
            return truncated

        inputs = self.summarizer_tokenizer(
            truncated,
            return_tensors="pt",
            truncation=True,
            max_length=1024,
        )
        summary_ids = self.summarizer_model.generate(
            inputs["input_ids"],
            min_length=20,
            max_length=60,
            do_sample=False,
        )
        return self.summarizer_tokenizer.decode(summary_ids[0], skip_special_tokens=True)

    # ------------------------------------------------------------------
    # TOC anchor detection
    # ------------------------------------------------------------------

    def _find_anchors(
            self,
            toc_data: list[dict],
            md_lines: list[str],
            ) -> list[tuple[int, dict]]:
        """Locate each TOC title in the Markdown file.

        Matching strategy (in order of preference):
            1. Exact match after basic normalisation (case + whitespace).
            2. Sequence similarity at or above ``match_threshold``.
            3. Keyword overlap fallback for truncated or split headings.

        Args:
            toc_data: Parsed TOC entries as loaded from the JSON file.
            md_lines: Lines of the Markdown document.

        Returns:
            A sorted list of ``(line_index, toc_entry)`` tuples.
        """
        anchors: list[tuple[int, dict]] = []

        for entry in toc_data:
            title = entry["title"]
            norm_full = " ".join(title.lower().split())
            norm_title = self._normalize(title)
            title_words = set(norm_title.split())

            best_idx = None
            best_ratio = 0.0

            for i, line in enumerate(md_lines):
                norm_line = " ".join(line.lower().split())
                norm_line_clean = self._normalize(line)

                # Strategy 1 — exact match
                if norm_line == norm_full:
                    best_idx = i
                    break

                # Strategy 2 — fuzzy sequence match
                if norm_title and norm_title in norm_line_clean:
                    ratio = difflib.SequenceMatcher(
                        None, norm_title, norm_line_clean
                    ).ratio()
                    if ratio > best_ratio and ratio >= self.match_threshold:
                        best_ratio = ratio
                        best_idx = i

            # Strategy 3 — keyword overlap fallback (handles truncated/split headings)
            if best_idx is None and title_words:
                for i, line in enumerate(md_lines):
                    norm_line_clean = self._normalize(line)
                    line_words = set(norm_line_clean.split())
                    if not line_words:
                        continue
                    overlap = len(title_words & line_words) / len(title_words)
                    if overlap > best_ratio and overlap >= self.match_threshold:
                        best_ratio = overlap
                        best_idx = i

            if best_idx is not None:
                anchors.append((best_idx, entry))
            else:
                logger.warning("Title not found in Markdown: %s", title)

        anchors.sort(key=lambda x: x[0])
        return anchors

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def analyze(self, uuid: str) -> dict[str, SectionAnalysis]:
        """Run semantic analysis on all sections of a whitepaper.

        Args:
            uuid: UUID of the document to analyse.

        Returns:
            A dictionary mapping section titles to :class:`SectionAnalysis` objects.

        Raises:
            FileNotFoundError: If the TOC or Markdown file does not exist for the given UUID.
        """
        if self._already_processed(uuid):
            logger.info("Skipping already processed document: %s", uuid)
            return self._load(uuid)

        toc_path = WhitepaperConfig.TOCS_DIR / f"{uuid}.json"
        md_path = WhitepaperConfig.MD_DIR / f"{uuid}.md"

        if not toc_path.exists():
            raise FileNotFoundError(f"TOC not found for UUID: {uuid}")
        if not md_path.exists():
            raise FileNotFoundError(f"Markdown file not found for UUID: {uuid}")

        with open(toc_path, encoding="utf-8") as f:
            toc_data = json.load(f)

        md_lines = md_path.read_text(encoding="utf-8").splitlines()
        anchors = self._find_anchors(toc_data, md_lines)

        if not anchors:
            logger.warning("No anchors found for UUID: %s", uuid)
            return {}

        results: dict[str, SectionAnalysis] = {}

        for i, (line_idx, entry) in enumerate(anchors):
            start = line_idx + 1
            end = anchors[i + 1][0] if i + 1 < len(anchors) else len(md_lines)
            content = "\n".join(md_lines[start:end]).strip()

            if not content:
                continue

            sentiment, score_str = self._analyze_sentiment(content)
            resume = self._summarize(content)

            results[entry["title"]] = SectionAnalysis(
                word_count=len(content.split()),
                sentiment=sentiment,
                score=score_str,
                resume=resume,
            )

        self._save(uuid, results)
        logger.info("Analysed %d sections for UUID: %s", len(results), uuid)
        return results